# Generated by Django 4.0.6 on 2022-07-23 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(choices=[('al', 'Albania'), ('ae', 'Arab Emirates'), ('at', 'Austria'), ('be', 'Belgium'), ('bg', 'Bulgaria'), ('hr', 'Croatia'), ('cz', 'Czech Republic'), ('dk', 'Denmark'), ('ee', 'Estonia'), ('fi', 'Finland'), ('fr', 'France'), ('de', 'Germany'), ('gr', 'Greece'), ('hk', 'Hong Kong'), ('hu', 'Hungary'), ('it', 'Italy'), ('lu', 'Luxembourg'), ('mo', 'Macau'), ('my', 'Malaysia'), ('nl', 'Netherlands'), ('no', 'Norway'), ('pk', 'Pakistan'), ('ph', 'Philippines'), ('pl', 'Poland'), ('rs', 'Serbia'), ('sg', 'Singapore'), ('sk', 'Slovakia'), ('si', 'Slovenia'), ('es', 'Spain'), ('se', 'Sweden'), ('ch', 'Switzerland'), ('th', 'Thailand'), ('ua', 'Ukraine'), ('gb', 'United Kingdom')], max_length=2, verbose_name='Country')),
                ('address', models.TextField(verbose_name='Address')),
                ('full_name', models.CharField(max_length=150, verbose_name='Full Name')),
                ('amount_payable', models.DecimalField(decimal_places=2, max_digits=6)),
                ('card_num', models.CharField(max_length=16, verbose_name='Card Number')),
                ('card_holder_name', models.CharField(max_length=50, verbose_name='Card Holder Name')),
                ('card_expired', models.CharField(max_length=50, verbose_name='Card Expired')),
                ('card_cvc', models.CharField(max_length=50, verbose_name='Card CVV')),
            ],
            options={
                'verbose_name': 'Card',
                'verbose_name_plural': 'Cards',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=100, verbose_name='Last Name')),
                ('email', models.EmailField(max_length=254, verbose_name='E-Mail')),
                ('phone', models.CharField(max_length=30, verbose_name='Phone number')),
                ('password', models.CharField(max_length=50, verbose_name='Password')),
                ('card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.card', verbose_name='Card')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
        ),
    ]
