COUNTRIES = [
        ('al', 'Albania'),
        ('ae', 'Arab Emirates'),
        ('at', 'Austria'),
        ('be', 'Belgium'),
        ('bg', 'Bulgaria'),
        ('hr', 'Croatia'),
        ('cz', 'Czech Republic'),
        ('dk', 'Denmark'),
        ('ee', 'Estonia'),
        ('fi', 'Finland'),
        ('fr', 'France'),
        ('de', 'Germany'),
        ('gr', 'Greece'),
        ('hk', 'Hong Kong'),
        ('hu', 'Hungary'),
        ('it', 'Italy'),
        ('lu', 'Luxembourg'),
        ('mo', 'Macau'),
        ('my', 'Malaysia'),
        ('nl', 'Netherlands'),
        ('no', 'Norway'),
        ('pk', 'Pakistan'),
        ('ph', 'Philippines'),
        ('pl', 'Poland'),
        ('rs', 'Serbia'),
        ('sg', 'Singapore'),
        ('sk', 'Slovakia'),
        ('si', 'Slovenia'),
        ('es', 'Spain'),
        ('se', 'Sweden'),
        ('ch', 'Switzerland'),
        ('th', 'Thailand'),
        ('ua', 'Ukraine'),
        ('gb', 'United Kingdom')
]
